### PR TITLE
New Post - SAML Documentation

### PR DESCRIPTION
**Pull request by cooncesean**
## Overview
Adding a new blog post around Guidebook's SSO (SAML) documentation.

## Changes 
In order for this documentation to look reasonable, I had to widen the width of the `.post` class selector (gaining about 180 pixels in the process). IMHO, this looks better across the board, but its something we should be aware of.

I also created a new `partial` template called `_includes/image-container.html`. This partial wraps an image in the appropriate tags and keeps the code more DRY.

## Refs
https://jira.guidebook.com/browse/BUIL-2168

## Testing
To check out these changes, pull down the branch and start your local gulp server. This should be the first post in the document.

cc @snide

### CODE REVIEW

**Comment by cooncesean** [comment]
Oh - and I don't know how to get my image to show up in the author header. @pklada can you tell me where that image should live within the project.

**Comment by pklada** [comment]
@cooncesean for the avatar, you have to have your slug match your slug on gb.com (in this case it would be scoonce)

**Comment by pklada** [comment]
@cooncesean fixed some styling as it related to h2s within the post body. I also set back (for now) the skinnier posts on the main eng summary page -- i like them pretty small/digestible there (not that this only affects that page, the posts are nice and wide when actually viewing their details). 

Everything else looks good, merge at will!

**Comment by cooncesean** [comment]
Noting that 8a2921122c1a0056f9ebf9602d4180602d8511ae added the SSO control flow image to the post.

This has been reviewed by both @pklada and @snide ... merging and pushing it out.

**Pull request merged**
